### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by alandipert** [gorillalabs/sparkling-getting-started#2]
Hello, 
When I run:

```
$ lein uberjar
$ java -jar target/sparkling-getting-started-1.0.0-SNAPSHOT-standalone.jar
```

I get an error like this:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
...
Caused by: java.lang.ClassNotFoundException: org.apache.spark.SparkConf
```

Is there a configuration or compilation step I'm missing or is this a bug?

I'm on Linux with openjdk 1.8.0_40, Leiningen 2.5.1.  Thanks for any help!

**Comment by chrisbetz** [comment]
Hi Alan,

sorry for taking so long. I’m not quite sure what you’re up to. In order to run locally, you need to have a spark dependency which is missing in your case.
The „normal“ config of sparkling is for running on a cluster, where spark or a spark assembly jar usually is provided (see ).

So, in order to get you up and running, you should add [org.apache.spark/spark-core_2.10 "1.2.1"]
together with whatever dependency is necessary for your code. Or use the spark-assembly from your distribution, if you’re using on on your cluster.

Good luck!

Chris

**Comment by alandipert** [comment]
Hey, thank you for your help with this!  We figured it out.

**Comment by octplane** [comment]
Me being a real spark newbie, let me thank you for this :+1:

**Comment by chrisbetz** [comment]
Oh, you're welcome. :)
